/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MENU;

import JUEGO.BOARD;
import USUARIO.ManagerUsuarios;
import USUARIO.Usuario;
import USUARIO.historial;
import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Josue Gavidia
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public static SimpleDateFormat fechaNeitor;
    public ManagerUsuarios managerUsers;
    public static ArrayList<String> PLAYERS, p1, p2, p3;
    public static ArrayList<Usuario> team1, team2, team3;
    public static int cantPlayersSettings, cantEquipos;
    public static boolean specialsPermited;
    public static String chosenColorT1, chosenColorT2, chosenColorT3;
    private String Loggeado;

    public MenuPrincipal() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.REG_TAB.setVisible(false);
        this.PLAY_TAB.setVisible(false);
        this.MAIN_MENU.setVisible(false);
        this.CONFIG_TAB.setVisible(false);
        this.REPORTS_TAB.setVisible(false);
        EQUIPO3.setVisible(false);
        this.playersThreeSc.setVisible(false);
        tokenColor3.setVisible(false);
        rem3.setVisible(false);

        try {
            managerUsers = new ManagerUsuarios();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        } catch (ClassNotFoundException e) {

        }
        PLAYERS = new ArrayList<>();
        p1 = new ArrayList<>();
        p2 = new ArrayList<>();
        p3 = new ArrayList<>();
        team1 = new ArrayList<>();
        team2 = new ArrayList<>();
        team3 = new ArrayList<>();
        cantPlayersSettings = 4;
        specialsPermited = false;
        cantEquipos = setCantidadEquipos(cantPlayersSettings);
        fechaNeitor = new SimpleDateFormat("dd/MM/yyyy");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_MENU = new javax.swing.JPanel();
        PLAY = new javax.swing.JButton();
        config = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        logOUT = new javax.swing.JButton();
        REG_TAB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        fullName = new javax.swing.JTextField();
        Reg_Checkout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        confPass = new javax.swing.JTextField();
        backToLogin = new javax.swing.JButton();
        LOG_IN = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        usLogin = new javax.swing.JTextField();
        passLogin = new javax.swing.JTextField();
        checkOut = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        PLAY_TAB = new javax.swing.JPanel();
        usersListSc = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();
        EQUIPO1 = new javax.swing.JButton();
        EQUIPO3 = new javax.swing.JButton();
        playesOneSc = new javax.swing.JScrollPane();
        playersOne = new javax.swing.JList<>();
        playersThreeSc = new javax.swing.JScrollPane();
        playersThree = new javax.swing.JList<>();
        tokenColor1 = new javax.swing.JComboBox<>();
        tokenColor2 = new javax.swing.JComboBox<>();
        EQUIPO2 = new javax.swing.JButton();
        playersTwoSc = new javax.swing.JScrollPane();
        playersTwo = new javax.swing.JList<>();
        tokenColor3 = new javax.swing.JComboBox<>();
        START = new javax.swing.JButton();
        rem1 = new javax.swing.JButton();
        rem2 = new javax.swing.JButton();
        rem3 = new javax.swing.JButton();
        backToMenu = new javax.swing.JButton();
        CONFIG_TAB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cantPCombo = new javax.swing.JComboBox<>();
        setCantJugadores = new javax.swing.JButton();
        RETURN = new javax.swing.JButton();
        REPORTS_TAB = new javax.swing.JPanel();
        playerDispReports = new javax.swing.JLabel();
        dateCreatedReports = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historialDisplay = new javax.swing.JTextArea();
        misc = new javax.swing.JLabel();
        backToMENU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        MAIN_MENU.setBackground(new java.awt.Color(51, 0, 0));
        MAIN_MENU.setPreferredSize(new java.awt.Dimension(1920, 1080));
        MAIN_MENU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PLAY.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        PLAY.setForeground(new java.awt.Color(255, 255, 255));
        PLAY.setText("JUGAR");
        PLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYActionPerformed(evt);
            }
        });
        MAIN_MENU.add(PLAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 330, 90));

        config.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        config.setForeground(new java.awt.Color(255, 255, 255));
        config.setText("CONFIGURACION");
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });
        MAIN_MENU.add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 330, 90));

        reportes.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setText("REPORTES");
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        MAIN_MENU.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, 330, 90));

        logOUT.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        logOUT.setText("CERRAR SESION");
        logOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOUTActionPerformed(evt);
            }
        });
        MAIN_MENU.add(logOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 960, 330, 90));

        REG_TAB.setBackground(new java.awt.Color(51, 0, 0));
        REG_TAB.setPreferredSize(new java.awt.Dimension(1920, 1080));
        REG_TAB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE COMPLETO");
        REG_TAB.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 350, 100));

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO");
        REG_TAB.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 230, 100));

        jLabel3.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEñA");
        REG_TAB.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 230, 100));

        us.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        us.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 550, 80));

        pass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 550, 80));

        fullName.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fullName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 550, 80));

        Reg_Checkout.setBackground(new java.awt.Color(255, 255, 255));
        Reg_Checkout.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        Reg_Checkout.setForeground(new java.awt.Color(0, 0, 0));
        Reg_Checkout.setText("REGISTRARSE");
        Reg_Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reg_CheckoutActionPerformed(evt);
            }
        });
        REG_TAB.add(Reg_Checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 780, 330, 90));

        jLabel7.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFIRMAR CONTRASEñA");
        REG_TAB.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 430, 100));

        confPass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        confPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(confPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 650, 550, 80));

        backToLogin.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        backToLogin.setText("REGRESAR");
        backToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginActionPerformed(evt);
            }
        });
        REG_TAB.add(backToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 970, 330, 90));

        LOG_IN.setBackground(new java.awt.Color(51, 0, 0));
        LOG_IN.setPreferredSize(new java.awt.Dimension(1920, 1080));
        LOG_IN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USUARIO");
        LOG_IN.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 230, 100));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CONTRASEñA");
        LOG_IN.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 230, 100));

        usLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        usLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LOG_IN.add(usLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 550, 80));

        passLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        passLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LOG_IN.add(passLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 550, 80));

        checkOut.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        checkOut.setText("INICIAR SESION");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        LOG_IN.add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 690, 330, 90));

        reg.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        reg.setText("REGISTRARME");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        LOG_IN.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 690, 310, 80));

        PLAY_TAB.setBackground(new java.awt.Color(51, 0, 0));
        PLAY_TAB.setPreferredSize(new java.awt.Dimension(1920, 1080));
        PLAY_TAB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usersListSc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        usersList.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        usersList.setForeground(new java.awt.Color(0, 0, 0));
        usersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        usersListSc.setViewportView(usersList);

        PLAY_TAB.add(usersListSc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 690, 760));

        EQUIPO1.setText("Equipo 1");
        EQUIPO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EQUIPO1ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(EQUIPO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 150, 50));

        EQUIPO3.setText("Equipo 3");
        EQUIPO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EQUIPO3ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(EQUIPO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 470, 150, 50));

        playersOne.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        playesOneSc.setViewportView(playersOne);

        PLAY_TAB.add(playesOneSc, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, 160, 150));

        playersThree.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        playersThreeSc.setViewportView(playersThree);

        PLAY_TAB.add(playersThreeSc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 550, 160, 150));

        tokenColor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROJO", "AZUL", "VERDE", "AMARILLO" }));
        tokenColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenColor1ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(tokenColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 160, 30));

        tokenColor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AZUL", "VERDE", "ROJO", "AMARILLO" }));
        tokenColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenColor2ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(tokenColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 380, 160, 30));

        EQUIPO2.setText("Equipo 2");
        EQUIPO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EQUIPO2ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(EQUIPO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 130, 150, 50));

        playersTwo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        playersTwoSc.setViewportView(playersTwo);

        PLAY_TAB.add(playersTwoSc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 210, 160, 150));

        tokenColor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDE", "ROJO", "AZUL", "AMARILLO" }));
        tokenColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenColor3ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(tokenColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 720, 160, 30));

        START.setText("CONTINUAR");
        START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STARTActionPerformed(evt);
            }
        });
        PLAY_TAB.add(START, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 820, 160, 70));

        rem1.setText("remover");
        rem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem1ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(rem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 210, 110, -1));

        rem2.setText("remover");
        rem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem2ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(rem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 210, 110, -1));

        rem3.setText("remover");
        rem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem3ActionPerformed(evt);
            }
        });
        PLAY_TAB.add(rem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 560, 110, -1));

        backToMenu.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        backToMenu.setText("REGRESAR");
        backToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuActionPerformed(evt);
            }
        });
        PLAY_TAB.add(backToMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 960, 330, 90));

        CONFIG_TAB.setBackground(new java.awt.Color(51, 0, 0));
        CONFIG_TAB.setPreferredSize(new java.awt.Dimension(1920, 1080));
        CONFIG_TAB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CANTIDAD DE JUGADORES");
        CONFIG_TAB.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 850, 90));

        cantPCombo.setBackground(new java.awt.Color(0, 102, 102));
        cantPCombo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        cantPCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "6", "8" }));
        cantPCombo.setSelectedIndex(2);
        CONFIG_TAB.add(cantPCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 780, 70));

        setCantJugadores.setBackground(new java.awt.Color(153, 0, 0));
        setCantJugadores.setText("HECHO");
        setCantJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCantJugadoresActionPerformed(evt);
            }
        });
        CONFIG_TAB.add(setCantJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 320, 80));

        RETURN.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        RETURN.setText("REGRESAR");
        RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNActionPerformed(evt);
            }
        });
        CONFIG_TAB.add(RETURN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 960, 330, 90));

        REPORTS_TAB.setBackground(new java.awt.Color(51, 0, 0));
        REPORTS_TAB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerDispReports.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        playerDispReports.setForeground(new java.awt.Color(255, 255, 255));
        playerDispReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        playerDispReports.setText("JUGADOR");
        REPORTS_TAB.add(playerDispReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 70));

        dateCreatedReports.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        dateCreatedReports.setForeground(new java.awt.Color(255, 255, 255));
        dateCreatedReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateCreatedReports.setText("Registrado en");
        REPORTS_TAB.add(dateCreatedReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 620, 70));

        historialDisplay.setColumns(20);
        historialDisplay.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        historialDisplay.setForeground(new java.awt.Color(0, 0, 0));
        historialDisplay.setRows(5);
        jScrollPane1.setViewportView(historialDisplay);

        REPORTS_TAB.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 1110, 770));

        misc.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        misc.setForeground(new java.awt.Color(255, 255, 255));
        misc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        misc.setText("HISTORIAL DE JUEGO");
        REPORTS_TAB.add(misc, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 670, 70));

        backToMENU.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        backToMENU.setText("REGRESAR");
        backToMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMENUActionPerformed(evt);
            }
        });
        REPORTS_TAB.add(backToMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 960, 330, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(REG_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PLAY_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LOG_IN, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CONFIG_TAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(REPORTS_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(REG_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PLAY_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LOG_IN, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CONFIG_TAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(REPORTS_TAB, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depurarListas(JList list) {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.clear();
        list.setModel(model);
    }
    private void PLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYActionPerformed
        p1.clear();
        p2.clear();
        p3.clear();
        team1.clear();
        team2.clear();
        team3.clear();
        depurarListas(playersOne);
        depurarListas(playersTwo);
        depurarListas(playersThree);
        this.PLAY_TAB.setVisible(true);
        this.MAIN_MENU.setVisible(false);
        MenuPrincipal.PLAYERS = managerUsers.listUsers();

        DefaultListModel model = new DefaultListModel();

        for (String user : PLAYERS) {
            model.addElement(user);
        }

        usersList.setModel(model);

        if (cantEquipos == 3) {
            EQUIPO3.setVisible(true);
            playersThreeSc.setVisible(true);
            tokenColor3.setVisible(true);
            rem3.setVisible(true);
        }else{
             EQUIPO3.setVisible(false);
            playersThreeSc.setVisible(false);
            tokenColor3.setVisible(false);
            rem3.setVisible(false);
        }


    }//GEN-LAST:event_PLAYActionPerformed

    private int setCantidadEquipos(int cplayers) {
        switch (cplayers) {
            case 2:
                return 2;
            case 3:
                return 2;
            case 4:
                return 2;
            case 6:
                return 3;
            case 8:
                return 2;

        }
        return -1;
    }
    private void Reg_CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reg_CheckoutActionPerformed
        try {

            if (!this.fullName.getText().isEmpty() && !this.us.getText().isEmpty() && !this.pass.getText().isEmpty() && !this.confPass.getText().isEmpty()) {
                if (ManagerUsuarios.SearchUser(this.us.getText()) == null) {
                    if (!confPass.getText().equals(pass.getText())) {
                        JOptionPane.showMessageDialog(null, "LAS CONTRASEñA NO COINCIDE");
                        return;
                    }
                    managerUsers.createUser(fullName.getText(), us.getText(), pass.getText());
                    JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO");
                    System.out.println(ManagerUsuarios.SearchUser(this.us.getText()).getNAME() + " Has been Registered");

                    //Limpieza de textFields
                    for (Component a : this.REG_TAB.getComponents()) {

                        if (a instanceof JTextField) {

                            JTextField text = (JTextField) a;
                            text.setText(null);
                        }

                    }
                    this.REG_TAB.setVisible(false);
                    this.LOG_IN.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "NOMBRE DE USUARIO EN USO");
                }

            } else {
                JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
            }
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_Reg_CheckoutActionPerformed

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        String user, pw;

        user = this.usLogin.getText();
        pw = this.passLogin.getText();
        try {
            if (!user.isEmpty() && !pw.isEmpty()) {
                Usuario temp = ManagerUsuarios.SearchUser(user);
                if (temp != null && user.equals(temp.getUsername()) && pw.equals(temp.getPassword())) {
                    JOptionPane.showMessageDialog(null, "Bienvenido " + temp.getNAME() + " ^ - ^");
                    this.Loggeado = temp.getUsername();

                    //Limpieza de Fields
                    for (Component a : this.LOG_IN.getComponents()) {

                        if (a instanceof JTextField) {

                            ((JTextField) a).setText(null);

                        }

                    }
                    this.LOG_IN.setVisible(false);
                    this.MAIN_MENU.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEñA INCORRECTO");
                }
            } else {
                JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
            }
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_checkOutActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        this.LOG_IN.setVisible(false);
        this.REG_TAB.setVisible(true);

    }//GEN-LAST:event_regActionPerformed

    private void insertPlayer(JList players, ArrayList<String> array) {
        DefaultListModel<String> mainList = new DefaultListModel<>();
        DefaultListModel<String> miniList = new DefaultListModel<>();

        array.add(usersList.getSelectedValue());
        for (String a : array) {
            miniList.addElement(a);
        }

        PLAYERS.remove(this.usersList.getSelectedValue());

        for (String a : PLAYERS) {
            mainList.addElement(a);
        }

        usersList.setModel(mainList);
        players.setModel(miniList);
        usersList.clearSelection();

    }

    private void removePlayer(JList<String> players, ArrayList<String> array) {
        DefaultListModel<String> mainList = new DefaultListModel<>();
        DefaultListModel<String> miniList = new DefaultListModel<>();

        array.remove(players.getSelectedValue());
        for (String a : array) {
            miniList.addElement(a);
        }

        PLAYERS.add(players.getSelectedValue());
        for (String a : PLAYERS) {
            mainList.addElement(a);
        }

        usersList.setModel(mainList);
        players.setModel(miniList);
        players.clearSelection();

    }

    private void EQUIPO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EQUIPO1ActionPerformed
        insertPlayer(playersOne, p1);


    }//GEN-LAST:event_EQUIPO1ActionPerformed

    private void EQUIPO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EQUIPO3ActionPerformed
        insertPlayer(playersThree, p3);
    }//GEN-LAST:event_EQUIPO3ActionPerformed

    private void EQUIPO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EQUIPO2ActionPerformed
        insertPlayer(playersTwo, p2);

    }//GEN-LAST:event_EQUIPO2ActionPerformed

    public boolean areTeamsEven() {

        if (p1.isEmpty() && p2.isEmpty() && p3.isEmpty()) {
            JOptionPane.showMessageDialog(null, "LLENE LOS EQUIPOS");
            return false;
        }

        switch (cantPlayersSettings) {
            case 2:
                return p1.size() == p2.size() && (p1.size() + p2.size()) == 2;
            case 3:
                return (p1.size() == p2.size() && p2.size() == p3.size()) && (p1.size() + p2.size() + p3.size()) == 3;
            case 4:
                return p1.size() == p2.size() && (p1.size() + p2.size()) == 4;
            case 6:
                return (p1.size() == p2.size() && p2.size() == p3.size()) && (p1.size() + p2.size() + p3.size()) == 6;
            case 8:
                return p1.size() == p2.size() && (p1.size() + p2.size()) == 8;
            default:
                return false;
        }
    }
    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed
        this.MAIN_MENU.setVisible(false);
        this.CONFIG_TAB.setVisible(true);
    }//GEN-LAST:event_configActionPerformed

    private void STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STARTActionPerformed
        if (chosenColorT1 == null && chosenColorT2 == null && chosenColorT3 == null) {
            chosenColorT1 = "ROJO";
            chosenColorT2 = "VERDE";
            chosenColorT3 = "AZUL";
        }

        try {
            if (!areTeamsEven()) {
                JOptionPane.showMessageDialog(null, "EQUIPOS MAL DISTRIBUIDOS");
                return;
            }

            //SetTeams
            setRealTeams();
            BOARD board = new BOARD();
            this.PLAY_TAB.setVisible(false);
            this.MAIN_MENU.setVisible(true);

        } catch (IOException | ClassNotFoundException ex) {
            System.out.println("ERROR" + ex.getMessage());
        }


    }//GEN-LAST:event_STARTActionPerformed

    public void setRealTeams() throws IOException, ClassNotFoundException {
        setRealTeams(p1, team1, 1);
        setRealTeams(p2, team2, 2);
        if(cantEquipos==3){
             setRealTeams(p3, team3, 3);
        }
       
    }

    private void setRealTeams(ArrayList<String> players, ArrayList<Usuario> realTeam, int team) throws IOException, ClassNotFoundException {
        for (String name : players) {
            Usuario temp = ManagerUsuarios.SearchUser(name);
            temp.setTeam(team);
            realTeam.add(temp);
        }
    }

    private void rem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem1ActionPerformed
        removePlayer(playersOne, p1);
    }//GEN-LAST:event_rem1ActionPerformed

    private void rem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem2ActionPerformed
        removePlayer(playersTwo, p2);
    }//GEN-LAST:event_rem2ActionPerformed

    private void rem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem3ActionPerformed
        removePlayer(playersThree, p3);
    }//GEN-LAST:event_rem3ActionPerformed

    private void tokenColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenColor1ActionPerformed
        chosenColorT1 = getColor(tokenColor1);
    }//GEN-LAST:event_tokenColor1ActionPerformed

    private void tokenColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenColor2ActionPerformed
        chosenColorT2 = getColor(tokenColor2);
    }//GEN-LAST:event_tokenColor2ActionPerformed

    private void tokenColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenColor3ActionPerformed
        chosenColorT3 = getColor(tokenColor3);
    }//GEN-LAST:event_tokenColor3ActionPerformed

    private void setCantJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCantJugadoresActionPerformed
        String item = (String) this.cantPCombo.getSelectedItem();
        int cant = Integer.parseInt(item);
        cantPlayersSettings = cant;
        if(cantPlayersSettings ==3||cantPlayersSettings==6){
            cantEquipos=3;
        }else{
            cantEquipos=2;
        }
        setCantJugadores.setBackground(Color.GREEN);
        System.out.println("CANT JUGADORES : " + cantPlayersSettings);

    }//GEN-LAST:event_setCantJugadoresActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        try {
            this.MAIN_MENU.setVisible(false);
            REPORTS_TAB.setVisible(true);
            initReports(this.Loggeado);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_reportesActionPerformed

    private void logOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOUTActionPerformed
        this.MAIN_MENU.setVisible(false);
        this.LOG_IN.setVisible(true);
    }//GEN-LAST:event_logOUTActionPerformed

    private void backToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginActionPerformed
       this.REG_TAB.setVisible(false);
       this.LOG_IN.setVisible(true);
    }//GEN-LAST:event_backToLoginActionPerformed

    private void backToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuActionPerformed
       this.PLAY_TAB.setVisible(false);
       this.MAIN_MENU.setVisible(true);
    }//GEN-LAST:event_backToMenuActionPerformed

    private void backToMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMENUActionPerformed
      this.REPORTS_TAB.setVisible(false);
      this.MAIN_MENU.setVisible(true);
    }//GEN-LAST:event_backToMENUActionPerformed

    private void RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNActionPerformed
        this.CONFIG_TAB.setVisible(false);
        this.MAIN_MENU.setVisible(true);
        this.setCantJugadores.setBackground(Color.RED);
    }//GEN-LAST:event_RETURNActionPerformed

    private void initReports(String userEnSesion) throws IOException, ClassNotFoundException {
        Usuario Logged = ManagerUsuarios.SearchUser(userEnSesion);
        this.playerDispReports.setText("JUGADOR EN SESION: " + userEnSesion);
        this.dateCreatedReports.setText("SE UNIO EN: " + fechaNeitor.format(Logged.getFechaCreacion()));
        if (Logged.getHistorial().isEmpty()) {
            this.historialDisplay.setText("AUN NO SE HAN REGISTRADO JUEGOS");
        } else {
            print(Logged, this.historialDisplay);
        }

    }

    private void print(Usuario logged, JTextArea text) {
        StringBuilder builder = new StringBuilder();
        for (historial report : logged.getHistorial()) {
            builder.append(report.toString()).append("\n");
        }
        text.setText(builder.toString());
    }

    private String getColor(JComboBox comb) {
        String item = comb.getSelectedItem().toString();

        switch (item) {
            case "ROJO":
                return item;
            case "AMARILLO":
                return item;
            case "AZUL":
                return item;
            case "VERDE":
                return item;
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONFIG_TAB;
    private javax.swing.JButton EQUIPO1;
    private javax.swing.JButton EQUIPO2;
    private javax.swing.JButton EQUIPO3;
    private javax.swing.JPanel LOG_IN;
    private javax.swing.JPanel MAIN_MENU;
    private javax.swing.JButton PLAY;
    private javax.swing.JPanel PLAY_TAB;
    private javax.swing.JPanel REG_TAB;
    private javax.swing.JPanel REPORTS_TAB;
    private javax.swing.JButton RETURN;
    private javax.swing.JButton Reg_Checkout;
    private javax.swing.JButton START;
    private javax.swing.JButton backToLogin;
    private javax.swing.JButton backToMENU;
    private javax.swing.JButton backToMenu;
    private javax.swing.JComboBox<String> cantPCombo;
    private javax.swing.JButton checkOut;
    private javax.swing.JTextField confPass;
    private javax.swing.JButton config;
    private javax.swing.JLabel dateCreatedReports;
    private javax.swing.JTextField fullName;
    private javax.swing.JTextArea historialDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOUT;
    private javax.swing.JLabel misc;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField passLogin;
    private javax.swing.JLabel playerDispReports;
    private javax.swing.JList<String> playersOne;
    private javax.swing.JList<String> playersThree;
    private javax.swing.JScrollPane playersThreeSc;
    private javax.swing.JList<String> playersTwo;
    private javax.swing.JScrollPane playersTwoSc;
    private javax.swing.JScrollPane playesOneSc;
    private javax.swing.JButton reg;
    private javax.swing.JButton rem1;
    private javax.swing.JButton rem2;
    private javax.swing.JButton rem3;
    private javax.swing.JButton reportes;
    private javax.swing.JButton setCantJugadores;
    private javax.swing.JComboBox<String> tokenColor1;
    private javax.swing.JComboBox<String> tokenColor2;
    private javax.swing.JComboBox<String> tokenColor3;
    private javax.swing.JTextField us;
    private javax.swing.JTextField usLogin;
    private javax.swing.JList<String> usersList;
    private javax.swing.JScrollPane usersListSc;
    // End of variables declaration//GEN-END:variables
}
