
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JUEGO;

import static JUEGO.Mazo.imageResizer;
import MENU.MenuPrincipal;
import USUARIO.Usuario;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Josue Gavidia
 */
public class BOARD extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form BOARD
     */
    public static Thread timerThread;
    int min = 1;
    int sec = 59;
    boolean timesUp = false;
    boardManager boardTK;
    Mazo deckTK;
    public static JPanel[] left, bottom, right;
    public static Usuario enTurno;
    public static int equipoTurn = 1;
    public static int cont = 0;
    public static JPanel L, R, B;
    public static JButton baraja;
    public static JLabel timer, turnador;

    public BOARD() throws IOException, ClassNotFoundException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        boardTK = new boardManager();
        this.BottomManojo.setVisible(false);
        boardTK.initBoard(tablero);
        tablero.setLocation(330, 190);
        boardTK.initPlayerCards(barLeft, barRight, barBottom);

        left = new JPanel[]{L1, L2, L2, L3, L4};
        right = new JPanel[]{R1, R2, R3, R4};
        bottom = new JPanel[]{B1, B2};
        baraja = BARAJA;

        this.leftManojo.setVisible(true);
        this.rightManojo.setVisible(true);
        if (MenuPrincipal.cantEquipos == 3) {
            this.BottomManojo.setVisible(true);
        }
        turnador = this.turnAnnouncer;

        turnarInternamente();
        L = leftManojo;
        R = rightManojo;
        B = BottomManojo;

        deckTK = new Mazo();
        deckTK.initBARAJA(BARAJA);
        deckTK.initManojos(leftManojo);
        deckTK.initManojos(rightManojo);
        if (MenuPrincipal.cantEquipos == 3) {
            deckTK.initManojos(BottomManojo);
        }

        Mazo.setManojo(leftManojo, rightManojo, this.BottomManojo, enTurno);
        this.setVisible(true);
        this.cantCards.setText(deckTK.deck.size() + "");
        timerThread = new Thread(this);
        timerThread.start();
        cementerio.setIcon(imageResizer("cardBack.png", cementerio));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tablero = new javax.swing.JPanel();
        barLeft = new javax.swing.JPanel();
        L1 = new javax.swing.JPanel();
        name_L1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        point1 = new javax.swing.JLabel();
        L2 = new javax.swing.JPanel();
        name_L2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        point2 = new javax.swing.JLabel();
        L3 = new javax.swing.JPanel();
        name_L3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        point3 = new javax.swing.JLabel();
        L4 = new javax.swing.JPanel();
        name_L4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        point4 = new javax.swing.JLabel();
        barBottom = new javax.swing.JPanel();
        B1 = new javax.swing.JPanel();
        name_L9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        pointB1 = new javax.swing.JLabel();
        B2 = new javax.swing.JPanel();
        name_L10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        pointB2 = new javax.swing.JLabel();
        barRight = new javax.swing.JPanel();
        R1 = new javax.swing.JPanel();
        name_L5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        pointR1 = new javax.swing.JLabel();
        R2 = new javax.swing.JPanel();
        name_L6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        pointR2 = new javax.swing.JLabel();
        R3 = new javax.swing.JPanel();
        name_L7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        pointR3 = new javax.swing.JLabel();
        R4 = new javax.swing.JPanel();
        name_L8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        pointR4 = new javax.swing.JLabel();
        rightManojo = new javax.swing.JPanel();
        r7 = new javax.swing.JButton();
        r3 = new javax.swing.JButton();
        r2 = new javax.swing.JButton();
        r1 = new javax.swing.JButton();
        r4 = new javax.swing.JButton();
        r5 = new javax.swing.JButton();
        r6 = new javax.swing.JButton();
        leftManojo = new javax.swing.JPanel();
        l1 = new javax.swing.JButton();
        l2 = new javax.swing.JButton();
        l3 = new javax.swing.JButton();
        l4 = new javax.swing.JButton();
        l5 = new javax.swing.JButton();
        l6 = new javax.swing.JButton();
        l7 = new javax.swing.JButton();
        BottomManojo = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        BARAJA = new javax.swing.JButton();
        turnAnnouncer = new javax.swing.JLabel();
        cantCards = new javax.swing.JLabel();
        timerDisplay = new javax.swing.JLabel();
        timerCont = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cementerio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablero.setPreferredSize(new java.awt.Dimension(1100, 700));
        tablero.setLayout(null);
        jPanel1.add(tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 810, 880));

        barLeft.setBackground(new java.awt.Color(51, 0, 0));
        barLeft.setLayout(new java.awt.GridLayout(4, 0, 0, 40));

        L1.setBackground(new java.awt.Color(0, 102, 102));
        L1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L1.setPreferredSize(new java.awt.Dimension(65, 540));
        L1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L1.setText("NAME");
        L1.add(name_L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("AAAAAAA");
        jPanel2.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("AAAAAAA");
        jPanel2.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("AAAAAAA");
        jPanel2.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("AAAAAAA");
        jPanel2.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("AAAAAAA");
        jPanel2.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("AAAAAAA");
        jPanel2.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("AAAAAAA");
        jPanel2.add(jLabel9);

        L1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 100));

        point1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        point1.setText("PUNTOS");
        L1.add(point1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barLeft.add(L1);

        L2.setBackground(new java.awt.Color(0, 102, 102));
        L2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L2.setPreferredSize(new java.awt.Dimension(65, 540));
        L2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L2.setText("NAME");
        L2.add(name_L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel12.setText("AAAAAAA");
        jPanel3.add(jLabel12);

        jLabel13.setText("AAAAAAA");
        jPanel3.add(jLabel13);

        jLabel14.setText("AAAAAAA");
        jPanel3.add(jLabel14);

        jLabel15.setText("AAAAAAA");
        jPanel3.add(jLabel15);

        jLabel16.setText("AAAAAAA");
        jPanel3.add(jLabel16);

        jLabel17.setText("AAAAAAA");
        jPanel3.add(jLabel17);

        jLabel18.setText("AAAAAAA");
        jPanel3.add(jLabel18);

        L2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 120));

        point2.setText("PUNTOS");
        L2.add(point2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barLeft.add(L2);

        L3.setBackground(new java.awt.Color(0, 102, 102));
        L3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L3.setPreferredSize(new java.awt.Dimension(65, 540));
        L3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L3.setText("NAME");
        L3.add(name_L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel21.setText("AAAAAAA");
        jPanel4.add(jLabel21);

        jLabel22.setText("AAAAAAA");
        jPanel4.add(jLabel22);

        jLabel23.setText("AAAAAAA");
        jPanel4.add(jLabel23);

        jLabel24.setText("AAAAAAA");
        jPanel4.add(jLabel24);

        jLabel25.setText("AAAAAAA");
        jPanel4.add(jLabel25);

        jLabel26.setText("AAAAAAA");
        jPanel4.add(jLabel26);

        jLabel27.setText("AAAAAAA");
        jPanel4.add(jLabel27);

        L3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 120));

        point3.setText("PUNTOS");
        L3.add(point3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barLeft.add(L3);

        L4.setBackground(new java.awt.Color(0, 102, 102));
        L4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        L4.setPreferredSize(new java.awt.Dimension(65, 540));
        L4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L4.setText("NAME");
        L4.add(name_L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel5.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel30.setText("AAAAAAA");
        jPanel5.add(jLabel30);

        jLabel31.setText("AAAAAAA");
        jPanel5.add(jLabel31);

        jLabel32.setText("AAAAAAA");
        jPanel5.add(jLabel32);

        jLabel33.setText("AAAAAAA");
        jPanel5.add(jLabel33);

        jLabel34.setText("AAAAAAA");
        jPanel5.add(jLabel34);

        jLabel35.setText("AAAAAAA");
        jPanel5.add(jLabel35);

        jLabel36.setText("AAAAAAA");
        jPanel5.add(jLabel36);

        L4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 120));

        point4.setText("PUNTOS");
        L4.add(point4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barLeft.add(L4);

        jPanel1.add(barLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 760));

        barBottom.setBackground(new java.awt.Color(51, 0, 0));
        barBottom.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        B1.setBackground(new java.awt.Color(0, 102, 102));
        B1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B1.setPreferredSize(new java.awt.Dimension(65, 540));
        B1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L9.setText("NAME");
        B1.add(name_L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("AAAAAAA");
        jPanel6.add(jLabel11);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("AAAAAAA");
        jPanel6.add(jLabel20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("AAAAAAA");
        jPanel6.add(jLabel29);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("AAAAAAA");
        jPanel6.add(jLabel38);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setText("AAAAAAA");
        jPanel6.add(jLabel47);

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel56.setText("AAAAAAA");
        jPanel6.add(jLabel56);

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel65.setText("AAAAAAA");
        jPanel6.add(jLabel65);

        B1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 120));

        pointB1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pointB1.setText("PUNTOS");
        B1.add(pointB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barBottom.add(B1);

        B2.setBackground(new java.awt.Color(0, 102, 102));
        B2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B2.setPreferredSize(new java.awt.Dimension(65, 540));
        B2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L10.setText("NAME");
        B2.add(name_L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel7.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel147.setText("AAAAAAA");
        jPanel7.add(jLabel147);

        jLabel148.setText("AAAAAAA");
        jPanel7.add(jLabel148);

        jLabel149.setText("AAAAAAA");
        jPanel7.add(jLabel149);

        jLabel150.setText("AAAAAAA");
        jPanel7.add(jLabel150);

        jLabel151.setText("AAAAAAA");
        jPanel7.add(jLabel151);

        jLabel152.setText("AAAAAAA");
        jPanel7.add(jLabel152);

        jLabel153.setText("AAAAAAA");
        jPanel7.add(jLabel153);

        B2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 120));

        pointB2.setText("PUNTOS");
        B2.add(pointB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barBottom.add(B2);

        jPanel1.add(barBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 910, 510, 160));

        barRight.setBackground(new java.awt.Color(51, 0, 0));
        barRight.setLayout(new java.awt.GridLayout(4, 0, 0, 40));

        R1.setBackground(new java.awt.Color(0, 102, 102));
        R1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        R1.setPreferredSize(new java.awt.Dimension(65, 540));
        R1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L5.setText("NAME");
        R1.add(name_L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel8.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("AAAAAAA");
        jPanel8.add(jLabel39);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("AAAAAAA");
        jPanel8.add(jLabel40);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("AAAAAAA");
        jPanel8.add(jLabel41);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("AAAAAAA");
        jPanel8.add(jLabel42);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setText("AAAAAAA");
        jPanel8.add(jLabel43);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setText("AAAAAAA");
        jPanel8.add(jLabel44);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setText("AAAAAAA");
        jPanel8.add(jLabel45);

        R1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 100));

        pointR1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pointR1.setText("PUNTOS");
        R1.add(pointR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barRight.add(R1);

        R2.setBackground(new java.awt.Color(0, 102, 102));
        R2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        R2.setPreferredSize(new java.awt.Dimension(65, 540));
        R2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L6.setText("NAME");
        R2.add(name_L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel9.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel48.setText("AAAAAAA");
        jPanel9.add(jLabel48);

        jLabel49.setText("AAAAAAA");
        jPanel9.add(jLabel49);

        jLabel50.setText("AAAAAAA");
        jPanel9.add(jLabel50);

        jLabel51.setText("AAAAAAA");
        jPanel9.add(jLabel51);

        jLabel52.setText("AAAAAAA");
        jPanel9.add(jLabel52);

        jLabel53.setText("AAAAAAA");
        jPanel9.add(jLabel53);

        jLabel54.setText("AAAAAAA");
        jPanel9.add(jLabel54);

        R2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 120));

        pointR2.setText("PUNTOS");
        R2.add(pointR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barRight.add(R2);

        R3.setBackground(new java.awt.Color(0, 102, 102));
        R3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        R3.setPreferredSize(new java.awt.Dimension(65, 540));
        R3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L7.setText("NAME");
        R3.add(name_L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel10.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel57.setText("AAAAAAA");
        jPanel10.add(jLabel57);

        jLabel58.setText("AAAAAAA");
        jPanel10.add(jLabel58);

        jLabel59.setText("AAAAAAA");
        jPanel10.add(jLabel59);

        jLabel60.setText("AAAAAAA");
        jPanel10.add(jLabel60);

        jLabel61.setText("AAAAAAA");
        jPanel10.add(jLabel61);

        jLabel62.setText("AAAAAAA");
        jPanel10.add(jLabel62);

        jLabel63.setText("AAAAAAA");
        jPanel10.add(jLabel63);

        R3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 120));

        pointR3.setText("PUNTOS");
        R3.add(pointR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barRight.add(R3);

        R4.setBackground(new java.awt.Color(0, 102, 102));
        R4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        R4.setPreferredSize(new java.awt.Dimension(65, 540));
        R4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_L8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_L8.setText("NAME");
        R4.add(name_L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel11.setLayout(new java.awt.GridLayout(2, 0, 25, 5));

        jLabel66.setText("AAAAAAA");
        jPanel11.add(jLabel66);

        jLabel67.setText("AAAAAAA");
        jPanel11.add(jLabel67);

        jLabel68.setText("AAAAAAA");
        jPanel11.add(jLabel68);

        jLabel69.setText("AAAAAAA");
        jPanel11.add(jLabel69);

        jLabel70.setText("AAAAAAA");
        jPanel11.add(jLabel70);

        jLabel71.setText("AAAAAAA");
        jPanel11.add(jLabel71);

        jLabel72.setText("AAAAAAA");
        jPanel11.add(jLabel72);

        R4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 120));

        pointR4.setText("PUNTOS");
        R4.add(pointR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 30));

        barRight.add(R4);

        jPanel1.add(barRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 120, 240, 760));

        rightManojo.setBackground(new java.awt.Color(51, 0, 0));
        rightManojo.setLayout(new java.awt.GridLayout(7, 0, 0, 20));

        r7.setBackground(new java.awt.Color(51, 0, 0));
        r7.setText("jButton1");
        r7.setBorder(null);
        r7.setBorderPainted(false);
        r7.setContentAreaFilled(false);
        rightManojo.add(r7);

        r3.setBackground(new java.awt.Color(51, 0, 0));
        r3.setText("jButton1");
        r3.setBorder(null);
        r3.setBorderPainted(false);
        r3.setContentAreaFilled(false);
        rightManojo.add(r3);

        r2.setBackground(new java.awt.Color(51, 0, 0));
        r2.setText("jButton1");
        r2.setBorder(null);
        r2.setBorderPainted(false);
        r2.setContentAreaFilled(false);
        rightManojo.add(r2);

        r1.setBackground(new java.awt.Color(51, 0, 0));
        r1.setText("jButton1");
        r1.setBorder(null);
        r1.setBorderPainted(false);
        r1.setContentAreaFilled(false);
        rightManojo.add(r1);

        r4.setBackground(new java.awt.Color(51, 0, 0));
        r4.setText("jButton1");
        r4.setBorder(null);
        r4.setBorderPainted(false);
        r4.setContentAreaFilled(false);
        rightManojo.add(r4);

        r5.setBackground(new java.awt.Color(51, 0, 0));
        r5.setText("jButton1");
        r5.setBorder(null);
        r5.setBorderPainted(false);
        r5.setContentAreaFilled(false);
        rightManojo.add(r5);

        r6.setBackground(new java.awt.Color(51, 0, 0));
        r6.setText("jButton1");
        r6.setBorder(null);
        r6.setBorderPainted(false);
        r6.setContentAreaFilled(false);
        rightManojo.add(r6);

        jPanel1.add(rightManojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 70, 170, 790));

        leftManojo.setBackground(new java.awt.Color(51, 0, 0));
        leftManojo.setLayout(new java.awt.GridLayout(7, 0, 0, 20));

        l1.setBackground(new java.awt.Color(51, 0, 0));
        l1.setText("jButton1");
        l1.setBorder(null);
        l1.setBorderPainted(false);
        l1.setContentAreaFilled(false);
        l1.setPreferredSize(new java.awt.Dimension(45, 23));
        leftManojo.add(l1);

        l2.setBackground(new java.awt.Color(51, 0, 0));
        l2.setText("jButton1");
        l2.setBorder(null);
        l2.setBorderPainted(false);
        l2.setContentAreaFilled(false);
        l2.setPreferredSize(new java.awt.Dimension(45, 23));
        l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ActionPerformed(evt);
            }
        });
        leftManojo.add(l2);

        l3.setBackground(new java.awt.Color(51, 0, 0));
        l3.setText("jButton1");
        l3.setBorder(null);
        l3.setBorderPainted(false);
        l3.setContentAreaFilled(false);
        l3.setPreferredSize(new java.awt.Dimension(45, 23));
        leftManojo.add(l3);

        l4.setBackground(new java.awt.Color(51, 0, 0));
        l4.setText("jButton1");
        l4.setBorder(null);
        l4.setBorderPainted(false);
        l4.setContentAreaFilled(false);
        l4.setPreferredSize(new java.awt.Dimension(45, 23));
        leftManojo.add(l4);

        l5.setBackground(new java.awt.Color(51, 0, 0));
        l5.setText("jButton1");
        l5.setBorder(null);
        l5.setBorderPainted(false);
        l5.setContentAreaFilled(false);
        l5.setPreferredSize(new java.awt.Dimension(45, 23));
        leftManojo.add(l5);

        l6.setBackground(new java.awt.Color(51, 0, 0));
        l6.setText("jButton1");
        l6.setBorder(null);
        l6.setBorderPainted(false);
        l6.setContentAreaFilled(false);
        l6.setPreferredSize(new java.awt.Dimension(45, 23));
        leftManojo.add(l6);

        l7.setBackground(new java.awt.Color(51, 0, 0));
        l7.setText("jButton1");
        l7.setBorder(null);
        l7.setBorderPainted(false);
        l7.setContentAreaFilled(false);
        l7.setPreferredSize(new java.awt.Dimension(45, 23));
        leftManojo.add(l7);

        jPanel1.add(leftManojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 170, 790));

        BottomManojo.setBackground(new java.awt.Color(51, 0, 0));
        BottomManojo.setLayout(new java.awt.GridLayout(1, 7, 20, 0));

        b1.setBackground(new java.awt.Color(51, 0, 0));
        b1.setText("jButton1");
        b1.setBorder(null);
        b1.setBorderPainted(false);
        b1.setContentAreaFilled(false);
        BottomManojo.add(b1);

        b2.setBackground(new java.awt.Color(51, 0, 0));
        b2.setText("jButton1");
        b2.setBorder(null);
        b2.setBorderPainted(false);
        b2.setContentAreaFilled(false);
        BottomManojo.add(b2);

        b3.setBackground(new java.awt.Color(51, 0, 0));
        b3.setText("jButton1");
        b3.setBorder(null);
        b3.setBorderPainted(false);
        b3.setContentAreaFilled(false);
        BottomManojo.add(b3);

        b4.setBackground(new java.awt.Color(51, 0, 0));
        b4.setText("jButton1");
        b4.setBorder(null);
        b4.setBorderPainted(false);
        b4.setContentAreaFilled(false);
        BottomManojo.add(b4);

        b5.setBackground(new java.awt.Color(51, 0, 0));
        b5.setText("jButton1");
        b5.setBorder(null);
        b5.setBorderPainted(false);
        b5.setContentAreaFilled(false);
        BottomManojo.add(b5);

        b6.setBackground(new java.awt.Color(51, 0, 0));
        b6.setText("jButton1");
        b6.setBorder(null);
        b6.setBorderPainted(false);
        b6.setContentAreaFilled(false);
        BottomManojo.add(b6);

        b7.setBackground(new java.awt.Color(51, 0, 0));
        b7.setText("jButton1");
        b7.setBorder(null);
        b7.setBorderPainted(false);
        b7.setContentAreaFilled(false);
        BottomManojo.add(b7);

        jPanel1.add(BottomManojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 920, 870, 120));

        BARAJA.setBackground(new java.awt.Color(51, 0, 0));
        BARAJA.setText("deck");
        BARAJA.setBorder(null);
        BARAJA.setBorderPainted(false);
        BARAJA.setContentAreaFilled(false);
        BARAJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BARAJAActionPerformed(evt);
            }
        });
        jPanel1.add(BARAJA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 910, 130, 160));

        turnAnnouncer.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        turnAnnouncer.setForeground(new java.awt.Color(255, 255, 255));
        turnAnnouncer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnAnnouncer.setText("TURNO DE X JUGADOR ");
        jPanel1.add(turnAnnouncer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 10, 450, 50));

        cantCards.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        cantCards.setForeground(new java.awt.Color(255, 255, 255));
        cantCards.setText("0");
        jPanel1.add(cantCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 870, 60, 50));

        timerDisplay.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        timerDisplay.setForeground(new java.awt.Color(255, 255, 255));
        timerDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerDisplay.setText("SIGUIENTE TURNO EN");
        jPanel1.add(timerDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 50));

        timerCont.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        timerCont.setForeground(new java.awt.Color(255, 255, 255));
        timerCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(timerCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 150, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESTANTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 870, 140, 50));

        cementerio.setBackground(new java.awt.Color(51, 0, 0));
        cementerio.setText("cementerio");
        cementerio.setBorder(null);
        cementerio.setBorderPainted(false);
        cementerio.setContentAreaFilled(false);
        cementerio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cementerioActionPerformed(evt);
            }
        });
        jPanel1.add(cementerio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 900, 120, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 960, 70, 50));

        jLabel74.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Ultima ");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 920, 90, 50));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {

        while (true) {
            if (boardManager.SEQUENCE) {
                timerThread = null;
                victory gane = new victory(boardManager.WINNER, boardManager.teamWin);
                gane.setVisible(true);
                this.dispose();
                break;
            }

            if (timesUp) {
                this.timerThread = null;
                break;
            }
            try {
                if (sec == 0) {
                    if (min == 0) {

                        min = 0;
                        sec = 59;
                        turnarEntreEquipos();
                        turnarInternamente();
                        Mazo.setManojo(this.leftManojo, this.rightManojo, this.BottomManojo, enTurno);

                    } else {
                        min--;
                        sec = 59;
                    }
                } else {

                    sec--;
                }

                if (sec < 10) {
                    this.timerCont.setText(("0" + min + ":0" + sec));
                } else {
                    this.timerCont.setText(("0" + min + ":" + sec));
                }

                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }

        }

    }


    private void BARAJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BARAJAActionPerformed
        if (Mazo.auxLastPcard == null) {
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA CARTA");
            return;
        }

        if (deckTK.deck.size() == 2) {
            deckTK.deck.clear();
            deckTK.setDeck();
            Collections.shuffle(deckTK.deck);
            deckTK.initBARAJA(BARAJA);
        }

        this.deckTK.robarCarta(BARAJA, cementerio);
        turnarEntreEquipos();
        turnarInternamente();
        Mazo.setManojo(this.leftManojo, this.rightManojo, this.BottomManojo, enTurno);
        System.out.println("Equipo en Turno " + equipoTurn);
        this.cantCards.setText(deckTK.deck.size() + "");
        min = 1;
        sec = 59;
        boardManager.cleanBorders(boardManager.board);

    }//GEN-LAST:event_BARAJAActionPerformed

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l2ActionPerformed

    private void cementerioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cementerioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cementerioActionPerformed

    public static void turnarInternamente() {
        switch (equipoTurn) {
            case 1:
                if (cont == MenuPrincipal.team1.size()) {
                    cont = 0;

                }
                enTurno = MenuPrincipal.team1.get(cont);
                cont++;

                turnador.setText("TURNO DE " + enTurno.getUsername());
                break;
            case 2:
                if (cont == MenuPrincipal.team2.size()) {
                    cont = 0;

                }
                enTurno = MenuPrincipal.team2.get(cont);
                turnador.setText("TURNO DE " + enTurno.getUsername());
                break;
            case 3:
                if (cont == MenuPrincipal.team3.size()) {
                    cont = 0;

                }
                enTurno = MenuPrincipal.team3.get(cont);
                turnador.setText("TURNO DE " + enTurno.getUsername());
                break;

        }
    }

    public static void turnarEntreEquipos() {
        int cant = MenuPrincipal.cantEquipos;

        if (cant == 2 && equipoTurn == 2) {
            equipoTurn = 1;
            return;
        }

        if (cant == 3 && equipoTurn == 3) {
            equipoTurn = 1;
            return;
        }

        equipoTurn++;
    }

    private void showPlayerCards(JPanel team, ArrayList<Usuario> players) {
        ArrayList<JPanel> panels = this.stripPanels(team);
        for (int i = 0; i < players.size(); i++) {
            ArrayList<JLabel> currentPanelLabels = this.stripLabels(panels.get(i));
            this.setInfo(currentPanelLabels.get(0), players.get(i));
            
        }
    }

    private ArrayList<JLabel> stripLabels(JPanel panel) {
        ArrayList<JLabel> labels = new ArrayList();
        for (Component label : panel.getComponents()) {
            if (label instanceof JLabel) {
                labels.add((JLabel) label);
            }
        }
        return labels;
    }

    private ArrayList<JPanel> stripPanels(JPanel panel) {
        ArrayList<JPanel> panels = new ArrayList();
        for (Component panelito : panel.getComponents()) {
            if (panelito instanceof JPanel) {
                panels.add((JPanel) panelito);
            }
        }
        return panels;
    }

    private void setInfo(JLabel label, Usuario player) {

        if (label.getText().equals("NAME")) {
            label.setText(player.getUsername());
        }
       
    }
    /**
     * @param args the command line arguments
     */
    //    public static void main(String args[]) {
    //        /* Set the Nimbus look and feel */
    //        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //         */
    //        try {
    //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //                if ("Nimbus".equals(info.getName())) {
    //                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                    break;
    //                }
    //            }
    //        } catch (ClassNotFoundException ex) {
    //            java.util.logging.Logger.getLogger(BOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (InstantiationException ex) {
    //            java.util.logging.Logger.getLogger(BOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (IllegalAccessException ex) {
    //            java.util.logging.Logger.getLogger(BOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //            java.util.logging.Logger.getLogger(BOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        }
    //        //</editor-fold>
    //
    //        /* Create and display the form */
    //        java.awt.EventQueue.invokeLater(new Runnable() {
    //            public void run() {
    //                try {
    //                    new BOARD().setVisible(true);
    //                } catch (IOException | ClassNotFoundException ex) {
    //                    System.out.println(ex.getMessage());
    //                }
    //            }
    //        });
    //    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel B1;
    private javax.swing.JPanel B2;
    private javax.swing.JButton BARAJA;
    private javax.swing.JPanel BottomManojo;
    private javax.swing.JPanel L1;
    private javax.swing.JPanel L2;
    private javax.swing.JPanel L3;
    private javax.swing.JPanel L4;
    private javax.swing.JPanel R1;
    private javax.swing.JPanel R2;
    private javax.swing.JPanel R3;
    private javax.swing.JPanel R4;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JPanel barBottom;
    private javax.swing.JPanel barLeft;
    private javax.swing.JPanel barRight;
    private javax.swing.JLabel cantCards;
    private javax.swing.JButton cementerio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton l1;
    private javax.swing.JButton l2;
    private javax.swing.JButton l3;
    private javax.swing.JButton l4;
    private javax.swing.JButton l5;
    private javax.swing.JButton l6;
    private javax.swing.JButton l7;
    private javax.swing.JPanel leftManojo;
    private javax.swing.JLabel name_L1;
    private javax.swing.JLabel name_L10;
    private javax.swing.JLabel name_L2;
    private javax.swing.JLabel name_L3;
    private javax.swing.JLabel name_L4;
    private javax.swing.JLabel name_L5;
    private javax.swing.JLabel name_L6;
    private javax.swing.JLabel name_L7;
    private javax.swing.JLabel name_L8;
    private javax.swing.JLabel name_L9;
    private javax.swing.JLabel point1;
    private javax.swing.JLabel point2;
    private javax.swing.JLabel point3;
    private javax.swing.JLabel point4;
    private javax.swing.JLabel pointB1;
    private javax.swing.JLabel pointB2;
    private javax.swing.JLabel pointR1;
    private javax.swing.JLabel pointR2;
    private javax.swing.JLabel pointR3;
    private javax.swing.JLabel pointR4;
    private javax.swing.JButton r1;
    private javax.swing.JButton r2;
    private javax.swing.JButton r3;
    private javax.swing.JButton r4;
    private javax.swing.JButton r5;
    private javax.swing.JButton r6;
    private javax.swing.JButton r7;
    private javax.swing.JPanel rightManojo;
    private javax.swing.JPanel tablero;
    private javax.swing.JLabel timerCont;
    private javax.swing.JLabel timerDisplay;
    private javax.swing.JLabel turnAnnouncer;
    // End of variables declaration//GEN-END:variables
}
