/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JUEGO;

import MENU.MenuPrincipal;
import USUARIO.ManagerUsuarios;
import USUARIO.Usuario;
import USUARIO.historial;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Josue Gavidia
 */
public class victory extends javax.swing.JFrame {

    /**
     * Creates new form victory
     *
     * @param winner
     */
    int teamGanador;

    public victory(String winner, int t) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.logo.setIcon(resizer("gane.png", logo));
        this.CAT.setIcon(resizer("neko.png", CAT));
        this.win.setText(winner);
        teamGanador = t;

    }

    private ImageIcon resizer(String imagePath, JLabel label) {
        ImageIcon neocard = new ImageIcon(imagePath);
        Image Scalecard = neocard.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        neocard = new ImageIcon(Scalecard);
        return neocard;
    }

    //Funcion para guardar reporrtes
    //fecha de Gane, puntos ganados, equipo en que jugo
    private ArrayList<Usuario> addReport(ArrayList<Usuario> players) {

        for (Usuario p : players) {

            p.getHistorial().add(new historial(boardManager.fechaGANE, 3, teamGanador));
            //depura las cartas para evitar un error molesto mas adelante
            p.getCartas().clear();
            System.out.println("HIST SIZE " + p.getHistorial().size());

        }
        return players;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        win = new javax.swing.JLabel();
        back2menu = new javax.swing.JButton();
        CAT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 2150, 310));

        win.setFont(new java.awt.Font("Ravie", 1, 60)); // NOI18N
        win.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        win.setText("AQUI VA EL GANADOR");
        jPanel1.add(win, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 1380, 110));

        back2menu.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        back2menu.setText("REGRESAR AL MENU PRINCIPAL");
        back2menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2menuActionPerformed(evt);
            }
        });
        jPanel1.add(back2menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 700, 570, 90));
        jPanel1.add(CAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 220, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<Usuario> getWinnerTeam(int num) {
        switch (this.teamGanador) {
            case 1:
                return MenuPrincipal.team1;
            case 2:
                return MenuPrincipal.team2;
            case 3:
                return MenuPrincipal.team3;

        }
        return null;
    }
    private void back2menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2menuActionPerformed

        try {

            updateHistorial(addReport(getWinnerTeam(teamGanador)));

            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(victory.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_back2menuActionPerformed

    private void updateHistorial(ArrayList<Usuario> team) throws IOException {

        for (Usuario player : team) {

            ManagerUsuarios.modifyUser(player);
        }
    }
    //    /**
    //     * @param args the command line arguments
    //     */
    //    public static void main(String args[]) {
    //        /* Set the Nimbus look and feel */
    //        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //         */
    //        try {
    //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //                if ("Nimbus".equals(info.getName())) {
    //                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                    break;
    //                }
    //            }
    //        } catch (ClassNotFoundException ex) {
    //            java.util.logging.Logger.getLogger(victory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (InstantiationException ex) {
    //            java.util.logging.Logger.getLogger(victory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (IllegalAccessException ex) {
    //            java.util.logging.Logger.getLogger(victory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //            java.util.logging.Logger.getLogger(victory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        }
    //        //</editor-fold>
    //
    //        /* Create and display the form */
    //        java.awt.EventQueue.invokeLater(new Runnable() {
    //            public void run() {
    //                new victory(boardManager.WINNER, boardManager.teamWin).setVisible(true);
    //            }
    //        });
    //    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CAT;
    private javax.swing.JButton back2menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
